module Loom.Verify
  ( Rank
  , Schedule
  , Capability
  , WaveOffset (..)
  , Shape
  , Array
  , Index
  , AccessCtx
  , DVec
  , Prog
  , Reducer
  , ReduceVar
  , shape1
  , shape2
  , shape3
  , rectIx1
  , rectIx2
  , rectIx3
  , extent1
  , extent2
  , extent3
  , newArray
  , fromList
  , toList
  , wrapArray
  , unwrapArray
  , parFor1D
  , parFor2D
  , parFor3D
  , parForTiled2D
  , parForTiled3D
  , parForWavefront2D
  , foldFor1D
  , rectReadAccess1D
  , rectReadAccess2D
  , rectWriteAccess1D
  , rectWriteAccess2D
  , rectReadWriteAccess1D
  , rectReadWriteAccess2D
  , newReducer
  , reduce
  , getReducer
  , readAt
  , readOffsetAt1D
  , readDVecAt1D
  , readDVecOffsetAt1D
  , writeAt
  , writeDVecAt1D
  , readWaveAt
  , writeWaveAt
  , rowOf
  , colOf
  , pairOf
  , tileOriginOf
  , tileLocalOf
  , waveCoordsOf
  , unIndex1
  , unIndex2
  , unIndex3
  , runProg
  , parallel
  , barrier
  , intSum
  , doubleSum
  ) where

import Loom.Internal.Verify
